modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/simply-kel/actionbarinfo/issues"
license="GPL 3.0"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "actionbarinfo"
version = "${version}"
displayURL = "https://modrinth.com/mod/abi"
displayName = "Action Bar Info"
updateJSONURL = "https://api.modrinth.com/updates/abi/forge_updates.json"
authors = "Kel Cuprum"
description = "Display info in action bar"
logoFile = "assets/actionbarinfo/icon.png"

[[dependencies.actionbarinfo]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.actionbarinfo]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"